# Generated by Django 3.0.8 on 2020-07-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0004_supporter_caseworker'),
        ('commitment', '0002_commitment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='supporter',
        ),
        migrations.AddField(
            model_name='commitment',
            name='supporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter'),
            preserve_default=False,
        ),
    ]
