# Generated by Django 3.0.8 on 2020-07-23 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0003_auto_20200723_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
