# Generated by Django 3.0.8 on 2020-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0006_auto_20200808_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
