# Generated by Django 3.0.8 on 2020-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0002_auto_20200808_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseworker',
            name='last_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
