# Generated by Django 3.0.8 on 2020-07-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='gender_type',
        ),
    ]
