# Generated by Django 3.0.8 on 2020-07-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('supporter', '0002_auto_20200722_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Gender'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
