# Generated by Django 3.0.8 on 2020-07-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0001_initial'),
        ('supporter', '0003_auto_20200723_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='caseworker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='caseworker.CaseWorker'),
            preserve_default=False,
        ),
    ]
