# Generated by Django 3.0.8 on 2020-07-31 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0001_initial'),
        ('supporter', '0006_auto_20200731_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterCwChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('new_cw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseworker.CaseWorker')),
                ('prev_cw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_ce', to='caseworker.CaseWorker')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
