# Generated by Django 3.0.8 on 2020-07-31 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0001_initial'),
        ('supporter', '0007_supportercwchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=150)),
                ('caseworker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caseworker.CaseWorker')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
