# Generated by Django 3.0.8 on 2020-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20200808_1727'),
        ('supporter', '0008_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='case',
            field=models.ManyToManyField(to='case.Case'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
