# Generated by Django 3.0.8 on 2020-10-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0009_auto_20201006_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='last_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
