# Generated by Django 3.0.8 on 2021-04-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0005_auto_20201030_1153'),
        ('case', '0005_auto_20200808_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.Recipient', unique=True),
        ),
    ]
