# Generated by Django 3.0.8 on 2020-07-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20200723_2043'),
        ('recipient', '0002_auto_20200723_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illness',
        ),
    ]
