# Generated by Django 3.0.8 on 2020-07-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supporter', '0003_auto_20200723_2032'),
        ('recipient', '0002_auto_20200723_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
                ('illness', models.ManyToManyField(to='recipient.Illness')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.Recipient')),
                ('supporter', models.ManyToManyField(to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
