# Generated by Django 3.0.8 on 2020-07-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20200723_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='supporter',
        ),
    ]
