# Generated by Django 3.0.8 on 2020-08-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0007_commitmentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='commitment.CommitmentAccount'),
        ),
    ]
