# Generated by Django 3.0.8 on 2020-10-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitment', '0007_commitmentaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitmentAccount',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='report_sent',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='report_wanted',
        ),
    ]
