# Generated by Django 3.0.8 on 2020-07-31 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0004_supporter_caseworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='mobile',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporter.Supporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
