# Generated by Django 3.0.8 on 2020-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0008_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
